<!DOCTYPE html>
<html lang="es">
<head>
	<title>Documentación</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="css/materialize.min.css">
</head>
<body>

<!--<div class="container">
	   		<a href="#" data-activates="nav-mobile" class="button-collapse top-nav full hide-on-large-only">
	   			<i class="mdi-navigation-menu" style="font-size:300%;"></i>
	   		</a>
	   	
      	<ul id="nav-mobile" class="side-nav fixed" style="width: 20%;">
        <li class="logo">
        	<a id="logo-container" href="#" class="brand-logo"><img src="people.png" width="60px"> </a>
        </li>
          <ul class="collapsible collapsible-accordion">
              <div class="collapsible-body" style="display: block;">
                <ul>
                  <li><a href="#">Inicio</a></li>
                  <li><a href="#">Datos</a></li>
                  <li><a href="#">Empresa</a></li>
                  <li><a href="#">Proyecto</a></li>
                  <li><a href="#">Informes</a></li>
                </ul>
              </div>
    	   </ul>
      	</ul>
      </div>-->
		<div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper blue-grey darken-3" >
        <a href="#" class="brand-logo">LOGO</a>
        <ul class="right hide-on-med-and-down">
              <li><a href="#">Inicio</a></li>
              <li><a href="index.php?c=controller&a=formData&; ?>">Mis Datos</a></li>
              <li><a href="index.php?c=controller&a=fillDataEnterpriseEs1&; ?">Estancias I</a></li>
              <li><a href="index.php?c=controller&a=fillDataEnterpriseEs2&; ?">Estancias II</a></li>
              <li><a href="index.php?c=controller&a=fillDataEnterpriseEstadias&; ?">Estadias</a></li>
              <li><a href="index.php?c=controller&a=closeSession&; ?">Cerrar sesion</a></li>
            </ul>
        <ul class="side-nav" id="nav-mobile">
              <li><a href="#">Inicio</a></li>
              <li><a href="index.php?c=controller&a=formData&; ?>">Mis Datos</a></li>
              <li><a href="index.php?c=controller&a=fillDataEnterpriseEs1&; ?">Estancias I</a></li>
              <li><a href="index.php?c=controller&a=fillDataEnterpriseEs2&; ?">Estancias II</a></li>
              <li><a href="index.php?c=controller&a=fillDataEnterpriseEstadias&; ?">Estadias</a></li>
              <li><a href="index.php?c=controller&a=closeSession&; ?">Cerrar sesion</a></li>
            </ul>
        <a class="button-collapse" href="#" data-activates="nav-mobile">
          <i class="mdi-navigation-menu"></i>
        </a>
      </div>
    </nav>
  </div>


      

    
            
      



